!function(e){if("object"==typeof exports)module.exports=e();else if("function"==typeof define&&define.amd)define(e);else{var f;"undefined"!=typeof window?f=window:"undefined"!=typeof global?f=global:"undefined"!=typeof self&&(f=self);var o=f;o=o.folktale||(o.folktale={}),o=o.data||(o.data={}),o.Maybe=e()}}(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by LiveScript 1.2.0
/** ^
 * Copyright (c) 2013 Quildreen "Sorella" Motta <quildreen@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
(function(){
  var Maybe, Just, Nothing;
  Maybe = (function(){
    Maybe.displayName = 'Maybe';
    var prototype = Maybe.prototype, constructor = Maybe;
    function Maybe(){}
    prototype.Nothing = function(){
      return Nothing;
    };
    prototype.Just = function(a){
      return new Just(a);
    };
    prototype.fromNullable = function(a){
      switch (false) {
      case a == null:
        return new Just(a);
      default:
        return Nothing;
      }
    };
    prototype.isNothing = false;
    prototype.isJust = false;
    prototype.of = function(a){
      return new Just(a);
    };
    prototype.ap = function(_){
      throw Error('unimplemented');
    };
    prototype.map = function(_){
      throw Error('unimplemented');
    };
    prototype.chain = function(_){
      throw Error('unimplemented');
    };
    prototype.toString = function(){
      throw Error('unimplemented');
    };
    prototype.isEqual = function(_){
      throw Error('unimplemented');
    };
    prototype.get = function(){
      throw Error('unimplemented');
    };
    prototype.getOrElse = function(_){
      throw Error('unimplemented');
    };
    prototype.orElse = function(_){
      throw Error('unimplemented');
    };
    return Maybe;
  }());
  Just = (function(superclass){
    var prototype = extend$((import$(Just, superclass).displayName = 'Just', Just), superclass).prototype, constructor = Just;
    function Just(value){
      this.value = value;
    }
    prototype.isJust = true;
    prototype.ap = function(b){
      return b.map(this.value);
    };
    prototype.map = function(f){
      return this.of(f(this.value));
    };
    prototype.chain = function(f){
      return f(this.value);
    };
    prototype.toString = function(){
      return "Maybe.Just(" + this.value + ")";
    };
    prototype.isEqual = function(a){
      return a.isJust && a.value === this.value;
    };
    prototype.get = function(){
      return this.value;
    };
    prototype.getOrElse = function(a){
      return this.value;
    };
    prototype.orElse = function(){
      return this;
    };
    return Just;
  }(Maybe));
  Nothing = new (function(superclass){
    var prototype = extend$(import$(constructor, superclass), superclass).prototype;
    function constructor(){}
    prototype.isNothing = true;
    prototype.ap = function(b){
      return b;
    };
    prototype.map = function(f){
      return this;
    };
    prototype.chain = function(f){
      return this;
    };
    prototype.toString = function(){
      return "Maybe.Nothing";
    };
    prototype.isEqual = function(a){
      return a.isNothing;
    };
    prototype.get = function(){
      throw new TypeError("Can't extract the value of a Nothing");
    };
    prototype.getOrElse = function(a){
      return a;
    };
    prototype.orElse = function(f){
      return f();
    };
    return constructor;
  }(Maybe));
  module.exports = new Maybe;
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);

},{}]},{},[1])
(1)
});
;